"""add producer and publisher columns to temporarily set real developers and publishers for seeding

Revision ID: 78e9684d2cc9
Revises: 6aa15cba39f8
Create Date: 2023-03-27 01:15:20.764680

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '78e9684d2cc9'
down_revision = '6aa15cba39f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('producer', sa.String(length=200), nullable=False))
    op.add_column('games', sa.Column('publisher', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###
    if environment == "production":
        op.execute(f"ALTER TABLE games SET SCHEMA {SCHEMA};")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'producer')
    op.drop_column('games', 'publisher')
    # ### end Alembic commands ###
