"""add is_refunded and price column to order_items table

Revision ID: b7597360a2a9
Revises: 82bed5b27d88
Create Date: 2023-03-05 12:55:50.020187

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = 'b7597360a2a9'
down_revision = '82bed5b27d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('is_refunded', sa.Boolean(), nullable=True))
    op.add_column('order_items', sa.Column('price', sa.Float(), nullable=False))
    # ### end Alembic commands ###
    if environment == "production":
        op.execute(f"ALTER TABLE order_items SET SCHEMA {SCHEMA};")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'price')
    op.drop_column('order_items', 'is_refunded')
    # ### end Alembic commands ###
