"""Add cart feature with relationships

Revision ID: 1f418a42bebe
Revises: b38168c841b2
Create Date: 2023-02-02 11:59:07.251693

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '1f418a42bebe'
down_revision = 'b38168c841b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('in_cart',
    sa.Column('games', sa.Integer(), nullable=False),
    sa.Column('carts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carts'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['games'], ['games.id'], ),
    sa.PrimaryKeyConstraint('games', 'carts')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE carts SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE in_cart SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('in_cart')
    op.drop_table('carts')
    # ### end Alembic commands ###
