"""Move preview/cover image to Game table from GameImage table

Revision ID: 6920ffdf51e9
Revises: 1f418a42bebe
Create Date: 2023-02-19 15:55:48.866739

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '6920ffdf51e9'
down_revision = '1f418a42bebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_images', 'is_preview')
    op.add_column('games', sa.Column('cover_image', sa.String(), nullable=False))

    if environment == "production":
        op.execute(f"ALTER TABLE games SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE game_images SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'cover_image')
    op.add_column('game_images', sa.Column('is_preview', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
