"""Game and Relationships

Revision ID: 4d88c914b766
Revises: ffdc0a98111c
Create Date: 2023-01-27 02:10:15.870320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d88c914b766'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('release_date', sa.Date(), nullable=False))
    op.drop_column('games', '_release_date')
    op.add_column('users', sa.Column('developer_alias', sa.String(length=40), nullable=True))
    op.create_unique_constraint(None, 'users', ['developer_alias'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'developer_alias')
    op.add_column('games', sa.Column('_release_date', sa.DATE(), nullable=False))
    op.drop_column('games', 'release_date')
    # ### end Alembic commands ###