"""adding thumbnail_url column to GameMedia

Revision ID: 6aa15cba39f8
Revises: bd3e0ad48c31
Create Date: 2023-03-20 00:20:21.793700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aa15cba39f8'
down_revision = 'bd3e0ad48c31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_media', sa.Column('thumbnail_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_media', 'thumbnail_url')
    # ### end Alembic commands ###