"""Add is_video column to GameMedia class to prepare for video uploading

Revision ID: bd3e0ad48c31
Revises: b7597360a2a9
Create Date: 2023-03-19 13:19:19.273645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd3e0ad48c31'
down_revision = 'b7597360a2a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_media', sa.Column('is_video', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_media', 'is_video')
    # ### end Alembic commands ###