"""update order_items table to include refund column

Revision ID: 8747bdaf74a0
Revises: 82bed5b27d88
Create Date: 2023-03-01 13:04:51.808613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8747bdaf74a0'
down_revision = '82bed5b27d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('is_refunded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'is_refunded')
    # ### end Alembic commands ###